/** Static action catalog — ported from poc-v1.jsx TECHNIQUES array.
 *  Bundled at build time, zero Firestore reads on the browse page.
 *  New community actions live in Firestore `acciones` collection.
 *
 *  Score ranges:
 *    arousal / trance / pleasure / dopamine / endorphins / oxytocin → -10 to 10
 *    energy → 0 to 10 (energy required by the action, not produced)
 *
 *  tags → space-separated string of lowercase slugs
 */

/**
 * @typedef {Object} Accion
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {string} hello_world
 * @property {string[]} common_errors
 * @property {string} [warning]
 * @property {number} arousal      -10 to 10
 * @property {number} trance       -10 to 10
 * @property {number} pleasure     -10 to 10
 * @property {number} dopamine     -10 to 10
 * @property {number} endorphins   -10 to 10
 * @property {number} oxytocin     -10 to 10
 * @property {number} energy        0 to 10 (energy required)
 * @property {string} arousal_why
 * @property {string} trance_why
 * @property {string} pleasure_why
 * @property {string} tags          space-separated slugs
 * @property {boolean} [_static]
 */

/** @type {Accion[]} */
export const ACTIONS = [
  { id:'vib-ext', name:'Vibración externa', description:'Vibrador en clítoris, frenillo o perineo. Sostenida induce trance leve por repetición.', hello_world:'Aplica vibrador de baja intensidad en zona genital externa. Mantén constante 10+ min.', common_errors:['Demasiada intensidad desde el inicio — empezar suave','Interrumpir antes de alcanzar el plateau'], arousal:7, trance:3, pleasure:8, dopamine:6, endorphins:4, oxytocin:2, energy:1, arousal_why:'Estimulación genital directa activa sistema simpático rápidamente.', trance_why:'La monotonía del estímulo continuo puede inducir trance leve.', pleasure_why:'Alta densidad de terminaciones nerviosas en zona genital.', tags:'sexual sex-toy sostenido accesible', _static:true },
  { id:'stim-int', name:'Estimulación interna', description:'G-spot o próstata. Placer difuso y profundo, favorece el trance. Requiere warm-up.', hello_world:'Estimulación de punto G o próstata con dedos o juguete específico tras 10-15 min de precalentamiento externo.', common_errors:['Sin warm-up previo no hay respuesta','Movimiento incorrecto — buscar presión sostenida no fricción'], arousal:5, trance:5, pleasure:7, dopamine:5, endorphins:5, oxytocin:3, energy:2, arousal_why:'Arousal moderado, sensación más difusa que estimulación externa.', trance_why:'El placer profundo y continuo favorece disociación leve.', pleasure_why:'Zonas internas tienen conexión directa al sistema nervioso parasimpático.', tags:'sexual sex-toy warm-up', _static:true },
  { id:'hands-free', name:'Orgasmo sin manos', description:'Respiración + kegels + fantasía + micro-movimientos. Trance muy alto porque no hay acción mecánica.', hello_world:'Combinar respiración conectada + contracciones pélvicas + visualización erótica durante 20-40 min.', common_errors:['Expectativas altas en primeras sesiones — requiere práctica','Interrumpir la respiración al aumentar el arousal'], warning:'No forzar si hay hiperventilación — pausar y respirar normal.', arousal:5, trance:8, pleasure:7, dopamine:7, endorphins:6, oxytocin:2, energy:4, arousal_why:'Sin estímulo físico externo, el arousal sube más lento pero de forma sostenida.', trance_why:'La ausencia de acción mecánica fuerza al sistema a voltearse hacia adentro.', pleasure_why:'El orgasmo sin contacto activa toda la red neuronal erógena de forma distribuida.', tags:'sexual sin-contacto respiracion avanzado no-se-necesita-nada', _static:true },
  { id:'estim', name:'Electro-estimulación', description:'Rango amplio según frecuencia e intensidad. La pérdida de control muscular favorece trance.', hello_world:'Empezar con TENS a intensidad mínima en muslos o glúteos antes de zonas más sensibles.', common_errors:['Saltar a zonas sensibles sin calibrar intensidad','Combinar con humedad sin equipo adecuado'], warning:'Nunca sobre el corazón ni por encima de la cintura con unidades no certificadas.', arousal:8, trance:5, pleasure:6, dopamine:7, endorphins:4, oxytocin:1, energy:1, arousal_why:'La impredictibilidad y pérdida de control muscular elevan el arousal significativamente.', trance_why:'La alternancia rítmica de sensación puede inducir estados disociativos.', pleasure_why:'Las contracciones involuntarias activan patrones placenteros en tejido muscular.', tags:'sexual sex-toy intenso bdsm', _static:true },
  { id:'asmr-tactil', name:'ASMR táctil / toque sutil', description:'Light touch, tracing. Activa respuesta meridiana. Mejor en nuca, antebrazos, detrás de las orejas.', hello_world:'Toque con yema de dedos o herramienta suave (peine, pincel) en nuca y antebrazos a velocidad muy lenta.', common_errors:['Presionar en vez de rozar','Velocidad demasiado rápida'], arousal:2, trance:7, pleasure:5, dopamine:3, endorphins:2, oxytocin:7, energy:0, arousal_why:'El arousal es bajo — el sistema se mantiene parasimpático.', trance_why:'La respuesta ASMR produce ondas alfa cerebrales similares a la meditación.', pleasure_why:'Activa fibras C-táctiles de contacto social, liberando oxitocina.', tags:'tacto sensorial sutil no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'masaje', name:'Auto-masaje profundo', description:'Trigger points: dolor seguido de release produce rush de placer por contraste.', hello_world:'Localizar zona tensa (hombros, caderas, pantorrillas), aplicar presión sostenida 30-90 seg hasta release.', common_errors:['Presión insuficiente para llegar al trigger point','Soltar antes del release'], arousal:3, trance:4, pleasure:6, dopamine:3, endorphins:6, oxytocin:4, energy:2, arousal_why:'El masaje baja la activación simpática salvo en los picos de presión.', trance_why:'El release muscular produce estados de relajación profunda repetibles.', pleasure_why:'La liberación del trigger point produce oleada de endorfinas localizada.', tags:'cuerpo relajacion accesible no-se-necesita-nada', _static:true },
  { id:'temperatura', name:'Juego de temperatura', description:'Hielo, cera, agua caliente. Puro arousal al inicio que se reatribuye. Alternancia calor/frío intensa.', hello_world:'Hielo en piel (muñecas, vientre, espalda), luego calor. Contrastar en ciclos de 30-60 seg.', common_errors:['Contacto demasiado prolongado con hielo en zonas sensibles','Cera muy caliente sin calibrar temperatura'], warning:'No aplicar hielo directo en piel más de 2-3 min — riesgo quemadura por frío.', arousal:7, trance:3, pleasure:4, dopamine:5, endorphins:4, oxytocin:1, energy:1, arousal_why:'El choque térmico activa el sistema simpático de forma inmediata.', trance_why:'El contraste rítmico puede crear estados alterados leves.', pleasure_why:'La reatribución del arousal térmico como excitación produce placer por contraste.', tags:'sensorial contraste accesible facil-de-complementar', _static:true },
  { id:'layering', name:'Layering erótico progresivo', description:'Empezar con 1 fuente, agregar una cada 5-10 min. El stacking gradual previene habituación.', hello_world:'Empezar con body-scan, agregar música, luego vibrador externo suave, luego fantasía — sin saturar.', common_errors:['Agregar todo a la vez — pierde el efecto de stacking','No dejar tiempo de meseta entre capas'], arousal:8, trance:7, pleasure:8, dopamine:8, endorphins:5, oxytocin:3, energy:3, arousal_why:'El stacking acumulativo eleva el arousal sin plateau de habituación.', trance_why:'La saturación gradual de canales sensoriales eventualmente rinde la prefrontal.', pleasure_why:'Múltiples fuentes de placer simultáneas activan más circuitos de recompensa.', tags:'sexual avanzado stacking sesion-completa facil-de-complementar', _static:true },
  { id:'edging-multi', name:'Edging multi-modal', description:'Al borde del orgasmo usando distinta modalidad cada vez: vibración, manos, fantasía, kegels.', hello_world:'Llevar al borde 3+ veces, cambiando la fuente de estimulación en cada ciclo. Ciclos de 5-10 min.', common_errors:['No cambiar la modalidad — reduce el efecto','Bajar demasiado entre ciclos'], arousal:9, trance:6, pleasure:9, dopamine:9, endorphins:3, oxytocin:2, energy:4, arousal_why:'El edging repetido mantiene el sistema simpático en nivel máximo sostenido.', trance_why:'La frustración controlada del orgasmo produce estados alterados de atención.', pleasure_why:'La dopamina acumulada en la anticipación hace el orgasmo final exponencialmente más intenso.', tags:'sexual avanzado edging intenso', _static:true },
  { id:'dolor', name:'Dolor controlado', description:'Pinzas, impacto, wax, agujas. Endorfinas + gate control + reatribución. Dolor rítmico favorece trance.', hello_world:'Comenzar con palmadas suaves en glúteos o pinzas de ropa en pezones. Calibrar umbral antes de escalar.', common_errors:['Escalar intensidad sin calibración activa','No establecer señal de parada clara'], warning:'Calibración activa permanente. No escalar sin feedback claro.', arousal:8, trance:5, pleasure:4, dopamine:6, endorphins:8, oxytocin:1, energy:3, arousal_why:'El dolor agudo activa el sistema simpático de forma masiva.', trance_why:'La liberación de endorfinas en dolor sostenido puede inducir estados similares al subspace.', pleasure_why:'El contraste dolor/alivio produce experiencia de placer intensa por reatribución.', tags:'bdsm intenso endorfinas', _static:true },
  { id:'miedo', name:'Miedo controlado', description:'Edge play, predicament bondage. El arousal upper más potente. Reatribución masiva.', hello_world:'Venda + no saber qué viene — con persona de confianza y acuerdo previo total. Empezar con suspenso narrativo.', common_errors:['Sin confianza previa establecida — activa trauma no reatribución','Sin salida clara de la situación'], warning:'Solo con persona de total confianza y acuerdos explícitos. No para principiantes.', arousal:9, trance:3, pleasure:1, dopamine:8, endorphins:5, oxytocin:0, energy:3, arousal_why:'El miedo es el activador simpático más potente que existe en el sistema nervioso.', trance_why:'El trance es bajo — la alerta del miedo mantiene la prefrontal activa.', pleasure_why:'El placer directo es bajo pero la reatribución post-experiencia puede ser enorme.', tags:'bdsm avanzado reatribucion', _static:true },
  { id:'ejercicio', name:'Ejercicio intenso breve', description:'Sprints, burpees, sentadillas. Arousal simpático reatribuible. Funciona como reset.', hello_world:'2-3 min de burpees o sentadillas a máxima velocidad antes de comenzar la sesión erótica.', common_errors:['Demasiado tiempo — cansancio cancela el efecto','Sin transición rápida a estimulación erótica'], arousal:7, trance:1, pleasure:2, dopamine:5, endorphins:5, oxytocin:0, energy:7, arousal_why:'El ejercicio intenso breve activa el sistema simpático de forma limpia y reatribuible.', trance_why:'El ejercicio en sí no produce trance — es un activador previo.', pleasure_why:'El placer directo es bajo pero el arousal pre-cargado amplifica todo lo que sigue.', tags:'cuerpo reset reatribucion rapido no-se-necesita-nada', _static:true },
  { id:'narrativa', name:'Tensión narrativa erótica', description:'Audio erótico con narrativa, role-play mental, escenarios elaborados. La mente como órgano sexual.', hello_world:'Audio erótico de alta calidad con narrativa (no solo sonidos) en auriculares + oscuridad + 20 min mínimo.', common_errors:['Audio de baja calidad o narrativa genérica','Interrupciones externas durante la inmersión'], arousal:6, trance:7, pleasure:5, dopamine:8, endorphins:2, oxytocin:4, energy:1, arousal_why:'La anticipación narrativa activa el sistema de recompensa dopaminérgico consistentemente.', trance_why:'La inmersión en narrativa suspende el monitoreo metacognitivo — trance por absorción.', pleasure_why:'El placer cerebral de la inmersión narrativa es altamente subjetivo y escalable.', tags:'mental audio inmersion no-se-necesita-nada', _static:true },
  { id:'resp-lenta', name:'Respiración lenta (4-7-8)', description:'Baja arousal sin bajar placer. Experiencia más ancha, menos urgente, más inmersiva.', hello_world:'Inhalar 4 seg, retener 7, exhalar 8. Repetir 4+ ciclos cuando el arousal sube demasiado rápido.', common_errors:['Hacerlo demasiado rígido — adaptar a propio ritmo','Abandonarlo al volver el arousal'], arousal:-4, trance:3, pleasure:1, dopamine:-1, endorphins:1, oxytocin:2, energy:0, arousal_why:'La respiración lenta activa el nervio vago y el sistema parasimpático directamente.', trance_why:'El foco en la respiración ancla la atención y reduce el diálogo interno.', pleasure_why:'El placer aumenta levemente al extender la duración de la estimulación.', tags:'respiracion regulacion accesible rapido no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'pausa', name:'Pausa con contacto mínimo', description:'Detener estimulación activa, mantener contacto pasivo. El silencio en la música.', hello_world:'Detener todo movimiento pero mantener la mano o el juguete en contacto. Esperar 2-3 min.', common_errors:['Reanudar antes de que baje el arousal','Perder el contacto físico completamente'], arousal:-5, trance:1, pleasure:0, dopamine:2, endorphins:0, oxytocin:3, energy:0, arousal_why:'La pausa activa elimina toda la estimulación simpática de forma inmediata.', trance_why:'El silencio activo tiene poco efecto trance en sí mismo.', pleasure_why:'La anticipación del retorno de la estimulación produce tensión placentera.', tags:'regulacion edging contraste no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'cold-down', name:'Cold down controlado', description:'Agua fría en cara/muñecas, hielo en nuca. Reset parasimpático rápido.', hello_world:'Agua fría en cara y muñecas durante 30 seg. Efecto inmediato.', common_errors:['Usar agua muy fría de golpe — puede crear pánico'], arousal:-6, trance:0, pleasure:0, dopamine:0, endorphins:2, oxytocin:0, energy:0, arousal_why:'El reflejo de inmersión facial activa el sistema parasimpático en segundos.', trance_why:'El reset de emergencia no produce estados alterados.', pleasure_why:'El contraste puede ser placentero pero el arousal cae significativamente.', tags:'reset emergencia rapido no-se-necesita-nada', _static:true },
  { id:'vib-sub', name:'Vibración sub-orgásmica sostenida', description:'Constante por debajo del umbral de orgasmo 20+ min. La mente se rinde, placer ambiental.', hello_world:'Vibrador a intensidad por debajo del umbral de orgasmo, sostenido 20-45 min sin cambios.', common_errors:['Subir intensidad cuando el arousal sube — perder el efecto','Menos de 15 min — no alcanza el plateau de rendición'], arousal:5, trance:8, pleasure:7, dopamine:4, endorphins:3, oxytocin:3, energy:1, arousal_why:'El arousal se estabiliza en nivel medio-alto y se sostiene sin subida.', trance_why:'La monotonía sensorial sostenida produce habituación prefrontal y apertura del trance.', pleasure_why:'El placer ambiental sostenido activa el sistema hedónico de forma difusa y duradera.', tags:'sexual sex-toy trance monotonia sostenido', _static:true },
  { id:'tambor', name:'Percusión rítmica 4.5Hz', description:'Tambor chamánico con auriculares. Ondas theta. Tradición chamánica adaptada.', hello_world:'Buscar "shamanic drumming 4.5hz" en YouTube/Spotify. Auriculares, oscuridad, posición cómoda. 20+ min.', common_errors:['Sin auriculares — pierde el efecto de inmersión','Interrupciones externas durante los primeros 10 min'], arousal:4, trance:8, pleasure:3, dopamine:3, endorphins:2, oxytocin:1, energy:0, arousal_why:'El ritmo constante mantiene un arousal leve y estable.', trance_why:'La frecuencia de 4-8Hz entraina ondas theta cerebrales directamente.', pleasure_why:'El placer directo es bajo pero el estado alterado puede potenciar otras prácticas.', tags:'audio trance theta no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'binaurales', name:'Binaural beats theta', description:'Frecuencias 4-8Hz, estado hipnagógico. Requiere auriculares.', hello_world:'Cualquier track de binaural beats theta en auriculares. 15+ min en posición relajada.', common_errors:['Sin auriculares estéreo no funciona','Esperarlo como un audio musical — es tecnología de entrenamiento cerebral'], arousal:2, trance:7, pleasure:2, dopamine:2, endorphins:1, oxytocin:1, energy:0, arousal_why:'El arousal es bajo — el objetivo es el estado theta no la activación.', trance_why:'Los binaural beats producen entrainment cerebral documentado hacia frecuencias theta.', pleasure_why:'El placer directo es bajo — su función es potenciar la profundidad de otras prácticas.', tags:'audio trance theta facil-de-complementar no-se-necesita-nada', _static:true },
  { id:'saturacion', name:'Saturación sensorial', description:'Múltiples estímulos a alta intensidad. La mente no puede procesar todo → se rinde → trance.', hello_world:'Música alta + vibrador + antifaz + restricción suave + narrativa simultáneamente. No agregar gradualmente — todo junto.', common_errors:['Agregar gradualmente — reduce el efecto de saturación','Sin restricción el cuerpo busca escapar de la sobrecarga'], warning:'Puede generar pánico en personas no acostumbradas. Empezar con versión suave.', arousal:9, trance:8, pleasure:6, dopamine:7, endorphins:5, oxytocin:2, energy:3, arousal_why:'La sobrecarga simultánea maximiza la activación simpática.', trance_why:'La mente no puede procesar múltiples canales simultáneamente — se rinde y produce disociación.', pleasure_why:'La saturación coordina múltiples fuentes de placer simultáneamente.', tags:'sexual avanzado intenso sobrecarga', _static:true },
  { id:'holotropica', name:'Respiración holotrópica', description:'20-45 min de respiración acelerada. Hormigueo, tetania, visiones, disolución.', hello_world:'Respiración circular rápida y profunda sin pausa. 20 min mínimo. Superficie blanda y segura.', common_errors:['Parar cuando aparece hormigueo — es el inicio del efecto','Posición incorrecta — necesita espacio para movimiento involuntario'], warning:'Mareos posibles. Superficie blanda. No hacer solo la primera vez. No con condiciones cardíacas.', arousal:8, trance:9, pleasure:4, dopamine:5, endorphins:6, oxytocin:2, energy:6, arousal_why:'La hiperventilación activa el sistema nervioso de forma masiva por alcalosis respiratoria.', trance_why:'La alcalosis respiratoria produce los estados alterados más profundos accesibles sin sustancias.', pleasure_why:'El placer es variable — la experiencia puede ser intensa pero no hedónica en sentido convencional.', tags:'respiracion avanzado visiones intenso no-se-necesita-nada', _static:true },
  { id:'privacion', name:'Privación sensorial', description:'Oscuridad + silencio + inmovilidad. La mente genera sus propios estímulos.', hello_world:'Habitación completamente oscura + tapones para los oídos + no moverse durante 20+ min.', common_errors:['Luz o ruido residual — rompe el efecto','Moverse cuando aparece incomodidad en vez de atravesarla'], arousal:2, trance:7, pleasure:2, dopamine:3, endorphins:1, oxytocin:1, energy:0, arousal_why:'El arousal es bajo — el sistema se desactiva al quitar todos los inputs externos.', trance_why:'Sin inputs externos, el cerebro comienza a generar sus propias alucinaciones hipnagógicas.', pleasure_why:'El placer directo es bajo pero la profundidad del estado potencia la visualización erótica.', tags:'privacion silencio visualizacion no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'privacion-visual', name:'Antifaz + estimulación', description:'Quitar visión concentra atención 100% en sensación corporal → amplificación.', hello_world:'Antifaz simple + cualquier estimulación. El efecto es inmediato y no requiere preparación.', common_errors:['Antifaz con luz residual — usar algo que bloquee completamente'], arousal:4, trance:6, pleasure:6, dopamine:4, endorphins:2, oxytocin:3, energy:0, arousal_why:'El arousal sube levemente al eliminar la distracción visual.', trance_why:'Sin input visual el foco en la sensación interna aumenta la profundidad del trance.', pleasure_why:'La amplificación de la sensación táctil al quitar la visión es inmediata y consistente.', tags:'privacion amplificacion accesible facil-de-complementar', _static:true },
  { id:'gazing', name:'Gazing (Trataka)', description:'Mirada fija a llama de vela sin parpadear. Trance visual, afterimages.', hello_world:'Vela a distancia de brazo, oscuridad, mirar sin parpadear 10-15 min. Las afterimages son el inicio.', common_errors:['Parpadear cuando los ojos lloran — atravesar la incomodidad','Interrumpir antes de que aparezcan las afterimages'], arousal:2, trance:7, pleasure:2, dopamine:2, endorphins:1, oxytocin:0, energy:1, arousal_why:'El gazing produce un estado de activación muy leve y sostenida.', trance_why:'El foco visual sostenido sin parpadeo produce estados hipnóticos bien documentados.', pleasure_why:'El placer directo es bajo — es principalmente una técnica de inducción.', tags:'visual meditacion foco no-se-necesita-nada', _static:true },
  { id:'body-scan', name:'Body scan erótico', description:'Atención lenta recorriendo el cuerpo. Amplifica cualquier sensación. Priming fundamental.', hello_world:'Cerrar ojos, llevar atención de pies a cabeza en 5-10 min. Notar cualquier sensación sin actuar. Ideal como inicio.', common_errors:['Hacerlo demasiado rápido','Saltear zonas de tensión en vez de detenerse en ellas'], arousal:2, trance:5, pleasure:4, dopamine:3, endorphins:1, oxytocin:3, energy:1, arousal_why:'El body scan eleva el arousal levemente al aumentar la conciencia corporal.', trance_why:'El foco interno sostenido produce absorción atencional y reduce el diálogo interno.', pleasure_why:'La atención dirigida amplifica las sensaciones existentes.', tags:'atencion priming accesible no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'narracion', name:'Amplificación por narración', description:'Describirse internamente lo que se siente en tiempo real. Dirige y sostiene la atención.', hello_world:'Durante cualquier estimulación, describir en silencio las sensaciones con detalle. "Siento calor en X, tensión en Y."', common_errors:['Narrar lo que debería sentirse en vez de lo que se siente'], arousal:2, trance:4, pleasure:3, dopamine:3, endorphins:0, oxytocin:1, energy:1, arousal_why:'La narración interna sube el arousal levemente al mantener el foco en la sensación.', trance_why:'El trance es moderado — la narración mantiene activa la parte descriptiva de la prefrontal.', pleasure_why:'Describir la sensación amplifica su percepción por mecanismo de atención dirigida.', tags:'mental atencion accesible no-se-necesita-nada facil-de-complementar', _static:true },
  { id:'micro-est', name:'Micro-dosis de estímulo', description:'Estimulación tan sutil que hay que esforzarse para sentirla. Fuerza hipersensibilización.', hello_world:'Toque de pluma o soplido de aire en piel. Intentar detectar exactamente dónde tocó. 10 min.', common_errors:['Estímulo demasiado fuerte — perder el efecto de búsqueda atencional'], arousal:1, trance:5, pleasure:3, dopamine:4, endorphins:0, oxytocin:2, energy:1, arousal_why:'El arousal es muy bajo — el sistema se mantiene en modo de escucha sensorial.', trance_why:'La concentración intensa en estímulos mínimos produce estados de absorción hipnótica.', pleasure_why:'La hipersensibilización producida amplifica el placer de estímulos posteriores.', tags:'sensorial priming sutil no-se-necesita-nada', _static:true },
  { id:'fantasia', name:'Role-play mental', description:'Escenario detallado, habitar un personaje con los 5 sentidos. Inmersión narrativa = trance.', hello_world:'Construir escenario erótico en detalle antes de comenzar. Entrar como personaje. Mantener los 5 sentidos activos.', common_errors:['Escenario vago — el cerebro necesita detalle para la inmersión','Salir del personaje al aumentar el arousal físico'], arousal:5, trance:7, pleasure:5, dopamine:7, endorphins:2, oxytocin:3, energy:2, arousal_why:'La fantasía elaborada activa el sistema dopaminérgico de anticipación de forma sostenida.', trance_why:'La inmersión en rol suspende la metacognición — trance por absorción narrativa.', pleasure_why:'El placer es subjetivo y altamente variable pero puede ser muy alto con escenarios bien construidos.', tags:'mental fantasia inmersion no-se-necesita-nada', _static:true },
  { id:'audio-erotico', name:'Audio erótico / ASMR erótico', description:'La voz guía atención y narrativa. Más inmersivo que video: requiere participación imaginativa.', hello_world:'Audio con narrativa erótica de calidad (no solo sonidos). Auriculares. Oscuridad. 15+ min sin interrupciones.', common_errors:['Audio de baja calidad o voces que rompen la inmersión','Con luz o pantalla visible — la visión compite con la imaginación'], arousal:5, trance:6, pleasure:5, dopamine:6, endorphins:1, oxytocin:4, energy:0, arousal_why:'La voz humana activa el sistema de apego y el arousal por procesamiento social.', trance_why:'La narrativa guiada en oscuridad produce absorción atencional sostenida.', pleasure_why:'La participación imaginativa activa las mismas redes que el placer físico.', tags:'audio narrativa inmersion no-se-necesita-nada', _static:true },
  { id:'orbit', name:'Microcosmic orbit', description:'Visualizar energía circulando: perineo → columna → coronilla → ombligo. Con práctica produce sensaciones reales.', hello_world:'Sentar cómodo. Imaginar calor subiendo por columna al inhalar, bajando por frente al exhalar. 15 min.', common_errors:['Forzar la sensación — se construye con práctica, no voluntad directa','Abandonar al no sentir nada las primeras sesiones'], arousal:3, trance:6, pleasure:4, dopamine:4, endorphins:2, oxytocin:2, energy:2, arousal_why:'El arousal es moderado y de naturaleza distinta — más energético que simpático.', trance_why:'La visualización sostenida de patrones corporales produce absorción atencional profunda.', pleasure_why:'Con práctica, las sensaciones visualizadas se vuelven físicamente perceptibles.', tags:'energetica meditacion practica no-se-necesita-nada', _static:true },
  { id:'breath-orgasm', name:'Breath orgasm (Carrellas)', description:'Respiración conectada + kegels + visualización de energía. Sin contacto genital.', hello_world:'Respiración circular rápida + kegels alternados + visualizar energía subiendo por columna. 30-45 min.', common_errors:['Pausar la respiración al aumentar el arousal','Enfocarse en el orgasmo como meta — bloquea el proceso'], warning:'Puede producir mareos. Empezar con sesiones de 20 min.', arousal:6, trance:8, pleasure:7, dopamine:6, endorphins:7, oxytocin:3, energy:5, arousal_why:'La combinación de hiperventilación leve y kegels eleva el arousal de forma sostenida.', trance_why:'La atención en el cuerpo energético produce estados de absorción muy profundos.', pleasure_why:'El orgasmo sin contacto activa toda la red neuronal erógena de forma distribuida y profunda.', tags:'sexual avanzado respiracion sin-contacto energetica no-se-necesita-nada', _static:true },
  { id:'cannabis', name:'Cannabis (dosis baja)', description:'Amplifica tacto, ralentiza tiempo subjetivo, favorece trance. Dosis baja.', hello_world:'Una inhalación o 2.5mg edible 30-60 min antes. Esperar el efecto antes de agregar otras prácticas.', common_errors:['Dosis alta — genera ansiedad no trance','Mezclar con otras prácticas antes de calibrar el propio efecto'], warning:'Dosis alta puede generar ansiedad intensa. Empezar con cantidades mínimas.', arousal:3, trance:5, pleasure:3, dopamine:4, endorphins:2, oxytocin:3, energy:0, arousal_why:'En dosis bajas el cannabis tiende a relajar el sistema simpático.', trance_why:'La disminución de la velocidad del tiempo subjetivo facilita la absorción atencional.', pleasure_why:'El cannabis amplifica las sensaciones táctiles de forma consistente.', tags:'droga amplificador facil-de-complementar', _static:true },
  { id:'mdma', name:'MDMA', description:'Empatía, apertura sensorial, tacto amplificado. Ventana 3-5h.', hello_world:'75-100mg primera vez, con persona de confianza, set y setting preparados. Nunca solo en primera vez.', common_errors:['Redosificar — aumenta el riesgo sin aumentar el efecto','Sin preparación de set y setting'], warning:'Mínimo 3 meses entre usos para evitar neurotoxicidad. No mezclar con inhibidores de MAO.', arousal:5, trance:3, pleasure:5, dopamine:7, endorphins:3, oxytocin:8, energy:4, arousal_why:'El MDMA eleva el arousal moderadamente a través del sistema noradrenérgico.', trance_why:'El trance es bajo — el MDMA produce apertura emocional no disociación.', pleasure_why:'La liberación masiva de serotonina y oxitocina produce placer relacional intenso.', tags:'droga empátogeno', _static:true },
  { id:'2cb', name:'2C-B', description:'El más erótico de los psicodélicos. Amplifica tacto sin confusión mental excesiva.', hello_world:'10-15mg, set y setting preparados, persona de confianza disponible. Primera vez en dosis baja.', common_errors:['Dosis alta — la experiencia se vuelve difícil de dirigir','Sin set y setting apropiado'], warning:'Set y setting fundamentales. No usar con antidepresivos.', arousal:5, trance:7, pleasure:6, dopamine:6, endorphins:3, oxytocin:4, energy:3, arousal_why:'El 2C-B eleva el arousal moderadamente preservando la función cognitiva.', trance_why:'El efecto psicodélico moderado produce estados alterados con claridad mental.', pleasure_why:'La amplificación táctil del 2C-B es específicamente erógena a diferencia de otros psicodélicos.', tags:'droga psicodelico', _static:true },
  { id:'poppers', name:'Poppers', description:'Rush de 30-90 seg. Vasodilatación, desinhibición. Booster puntual.', hello_world:'Una inhalación de 2-3 segundos. Efecto en 10-30 seg. Repetir cuando baje el efecto.', common_errors:['Inhalación prolongada — mareos y dolor de cabeza','Derramar sobre la piel — quemadura química'], warning:'No combinar con Viagra/Cialis/sildenafil — riesgo de hipotensión severa.', arousal:5, trance:3, pleasure:3, dopamine:4, endorphins:2, oxytocin:1, energy:0, arousal_why:'La vasodilatación produce rush de sangre y desinhibición rápidos.', trance_why:'El efecto es demasiado breve para producir trance significativo.', pleasure_why:'La desinhibición momentánea amplifica las sensaciones del momento.', tags:'droga booster rapido facil-de-complementar', _static:true },
  { id:'ketamina', name:'Ketamina (sub-hole)', description:'Disociación, flotar, cuerpo extraño y nuevo.', hello_world:'20-50mg intranasal en superficie segura con persona de confianza. Primera vez en dosis mínima.', common_errors:['Dosis alta — desconexión total del cuerpo','Solo o en entorno no seguro'], warning:'Dosis alta desconecta del cuerpo — pérdida de capacidad de comunicación. Solo con persona de confianza.', arousal:-2, trance:8, pleasure:2, dopamine:2, endorphins:1, oxytocin:1, energy:0, arousal_why:'La disociación producida por la ketamina desactiva la respuesta simpática.', trance_why:'La disociación disociativa de la ketamina es el trance más profundo farmacológicamente accesible.', pleasure_why:'El placer directo es bajo — la experiencia es principalmente de disolución y flotación.', tags:'droga disociativo', _static:true },
];

/** Busca una acción en el catálogo estático por id.
 * @param {string} id
 * @returns {Accion | undefined}
 */
export function findStatic(id) {
  return ACTIONS.find(a => a.id === id);
}

/** Devuelve todos los tags únicos del catálogo estático.
 * @returns {string[]}
 */
export function allStaticTags() {
  const set = new Set();
  ACTIONS.forEach(a => a.tags.split(' ').forEach(t => t && set.add(t)));
  return [...set].sort();
}
